### ISSUE TITLE
AIOUSB_GetVersion resturns incorrect text in python

### ISSUE THREAD

**Issue by rlegault33** [accesio/AIOUSB#13]
version: c759c87967632b948f78f2e198db113dccf54d60
>>> import AIOUSB
>>> AIOUSB.AIOUSB_GetVersion()
'$Format: %t$'

>>> AIOUSB.AIOUSB_GetVersionDate()
'$Format: %ad$'

**Comment by accesio** [comment]
This is because you are testing on Git master instead of a Tar'd / zipped release
