### ISSUE TITLE
udev rules on gentoo linux

### ISSUE THREAD

**Issue by josiah47** [accesio/AIOUSB#14]
I had to change some things to get this working automatically on usb plug in.

After much testing with udevadm monitor test and trigger I have figured out that I need to change
file name from 10-acces_usb.rules to 99-acces_usb.rules,

guess something else in the system was preventing the rules from being applied.

**Comment by accesio** [comment]
I tried out the Latest Gentoo linux had didn't see the problem you are describing.

I successfully ran against the Latest AMD64 boot off of the Gentoo website with  Hybrid ISO Live DVD AMD64.  

My steps to repeat this were:

1. Download livedvd-x86-amd64-32ul-20140826.iso
2. Burn to DVD / USB ( in my case USB ).
3. Live boot
4. git clone http://github/com/accesio/AIOUSB
5. build AIOUSB
6. git clone http://github.com/accesio/fxload
7. build fxload and install it 
8. cp AIOUSB/Firmware/*.hex /usr/share/usb
9. cp AIOUSB/Firmware/10-acces_usb.rules /etc/udev/rules.d
10. plug in USB-AIO16-16A and green light turned on 
11. Run samples
