### ISSUE TITLE
Update API Documentation

### ISSUE THREAD

**Issue by josiah47** [accesio/AIOUSB#15]
It seem the docs are out of date for particulary DIO_Read1
from http://accesio.com/MANUALS/USB%20Software%20Reference.pdf

it does not match what is in AIOUSB_DIO.h

also local git checkout for AIOUSB/lib/doc/Reference.html

seem to be too, but I don't know if this is because I need to update doxygen or not. i did make all the libs and the examples though.

Thanks,

**Comment by accesio** [comment]
Hi,

I've pushed a latest version of the API to the master branch 4d82e0f.  This should straighten out the inconsistency between the Linux API and the one documented on http://accesio.com/MANUALS/USB%20Software%20Reference.pdf  .  Please let me know if you discover any other inconsistencies.

-Jimi
