### ISSUE TITLE
DIO_Read* not returning correct data

### ISSUE THREAD

**Issue by josiah47** [accesio/AIOUSB#16]
i have tried my hand at writing a DIO_Read test program.

Can you confirm that if I set the the DIO ports to be Output and then set them to 0 or 1  that i could read that back in with DIO_Read1, DIO_Read8 or DIO_ReadAll?

Also which sample program would you recommend for reading. I do have writing working because I have hooked up a multimeter to the outputs to confirm they are actually getting set.

If so then I will need to keep trying.

Currently trying on 
Product ID: 0x8140
Product name: USB-AIO16-16A

**Comment by josiah47** [comment]
Okay it seems that DIO_ReadIntoDIOBuf works but DIO_Read8 returns different values each time
  
    DIO_Write1(deviceIndex,2,AIOUSB_TRUE);
    DIO_Write1(deviceIndex,3,AIOUSB_TRUE);
    DIO_Write1(deviceIndex,0,AIOUSB_TRUE);
    DIO_Write1(deviceIndex,1,AIOUSB_TRUE);

    DIOBuf *buf= NewDIOBuf(0);
    int cdat;
    DIO_ReadIntoDIOBuf( deviceIndex, buf );
    qDebug() << QString("Binary was: %1").arg(DIOBufToString( buf ));
    qDebug() << QString("Hex was: %1").arg(DIOBufToHex( buf ));
    DIO_Read8( deviceIndex, 0, &cdat  );
    qDebug() << QString("Single data was : hex:%1, int:%2").arg((int)cdat, 0, 16).arg((int)cdat, 0, 10);
    DIO_Read8( deviceIndex, 1, &cdat  );
    qDebug() << QString("Single data was : hex:%1, int:%2").arg((int)cdat, 0, 16).arg((int)cdat, 0, 10);

result of triggering sequentially 6 times 1 second apart

"Binary was: 0000111100000000" 
"Hex was: 0x0f00" 
"Single data was : hex:0, int:0" 
"Single data was : hex:6d, int:109" 
"Binary was: 0000111100000000" 
"Hex was: 0x0f00" 
"Single data was : hex:0, int:0" 
"Single data was : hex:65, int:101" 
"Binary was: 0000111100000000" 
"Hex was: 0x0f00" 
"Single data was : hex:0, int:0" 
"Single data was : hex:ffffffffffffff93, int:-109" 
"Binary was: 0000111100000000" 
"Hex was: 0x0f00" 
"Single data was : hex:0, int:0" 
"Single data was : hex:ffffffffffffff92, int:-110" 
"Binary was: 0000111100000000" 
"Hex was: 0x0f00" 
"Single data was : hex:0, int:0" 
"Single data was : hex:ffffffffffffffa6, int:-90" 
"Binary was: 0000111100000000" 
"Hex was: 0x0f00" 
"Single data was : hex:0, int:0" 
"Single data was : hex:69, int:105"

I am on Gentoo Linux 64bit

**Comment by accesio** [comment]
I've released a sample test program that assists with getting DIO working on a USB-AIO board. The sample is called dio_sample.c and it is available with version cde867b

After you configure your output channels, you will also be able to use the function DIO_ReadIntoDIOBuf();
