### ISSUE TITLE
AIOUSB_SetAllGainCodeAndDiffMode does not work as expected

### ISSUE THREAD

**Issue by josiah47** [accesio/AIOUSB#17]
each channel should be "gain":"0-2V" which it is not, I have confirmed this by reading a Bulk poll in whith a know voltage source and is indeed not reading in the 0-2V range...

    ADConfigBlock configBlock;
    AIOUSB_InitConfigBlock( &configBlock, deviceIndex, AIOUSB_FALSE );
    AIOUSB_SetAllGainCodeAndDiffMode( &configBlock, AD_GAIN_CODE_0_2V, AIOUSB_FALSE );
    ADCConfigBlockSetCalMode( &configBlock, AD_CAL_MODE_NORMAL );
    ADCConfigBlockSetTriggerMode( &configBlock, AD_TRIGGER_SCAN );
    AIOUSB_SetScanRange( &configBlock, 0, 4 );
    ADCConfigBlockSetOversample( &configBlock, 0 );
    int result = ADC_SetConfig( deviceIndex, configBlock.registers, &configBlock.size );
    qDebug() << ADCConfigBlockToJSON(&configBlock);

the qDebug spits out this
{"adcconfig":{"channels":[{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"}],"calibration":"Normal","trigger":{"reference":"sw","edge":"rising-edge","refchannel":"all-channels"},"start_channel":"0","end_channel":"4","oversample":"0","timeout":"5000","clock_rate":"1000"}}

    ADConfigBlock configBlock;
    AIOUSB_InitConfigBlock( &configBlock, deviceIndex, AIOUSB_FALSE );
    AIOUSB_SetDifferentialMode( &configBlock, 0, AIOUSB_FALSE);
    AIOUSB_SetDifferentialMode( &configBlock, 1, AIOUSB_FALSE);
    AIOUSB_SetDifferentialMode( &configBlock, 2, AIOUSB_FALSE);
    AIOUSB_SetDifferentialMode( &configBlock, 3, AIOUSB_FALSE);
    AIOUSB_SetDifferentialMode( &configBlock, 4, AIOUSB_FALSE);
    AIOUSB_SetGainCode( &configBlock, 0, AD_GAIN_CODE_0_2V);
    AIOUSB_SetGainCode( &configBlock, 1, AD_GAIN_CODE_0_2V);
    AIOUSB_SetGainCode( &configBlock, 2, AD_GAIN_CODE_0_2V);
    AIOUSB_SetGainCode( &configBlock, 3, AD_GAIN_CODE_5V);
    AIOUSB_SetGainCode( &configBlock, 4, AD_GAIN_CODE_5V);
    ADCConfigBlockSetCalMode( &configBlock, AD_CAL_MODE_NORMAL );
    ADCConfigBlockSetTriggerMode( &configBlock, AD_TRIGGER_SCAN );
    AIOUSB_SetScanRange( &configBlock, 0, 4 );
    ADCConfigBlockSetOversample( &configBlock, 0 );
    int result = ADC_SetConfig( deviceIndex, configBlock.registers, &configBlock.size );
    qDebug() << ADCConfigBlockToJSON(&configBlock);

the qDebug spits out this
{"adcconfig":{"channels":[{"gain":"0-2V"},{"gain":"0-2V"},{"gain":"0-2V"},{"gain":"+-5V"},{"gain":"+-5V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"}],"calibration":"Normal","trigger":{"reference":"sw","edge":"rising-edge","refchannel":"all-channels"},"start_channel":"0","end_channel":"4","oversample":"0","timeout":"5000","clock_rate":"1000"}}

I confirmed reading back the data with GetConfig and then outputting in JSON again and the settings are the same as before setting the config.

**Comment by accesio** [comment]
So, this was a bug in the checking code. It was quickly erroring out and while it was being reported back, it is easy to miss that.  Now this should be working as expected and I have added a Unit test to check for this going forward.

The fix has been released as 3132b85.

**Comment by accesio** [comment]
I am closing this since I haven't heard back and I believe that the fix plus unit test case catch this now.
