### ISSUE TITLE
Negative values being displayed as zeros.

### ISSUE THREAD

**Issue by josiah47** [accesio/AIOUSB#18]
Seems to be when using a battery as a voltage source on channel 4 or any channel for that matter configured with gain +-2V it only displays the positive voltage. battery + hooked to pin 7, battery - hooked to pin 8 on USB-AIO16-16A.

I have hacked the bulk_acquire_sample to produce this, http://pastebin.com/9EB3GjM3
i have commeted out the line
AIOUSB_SetAllGainCodeAndDiffMode( &configBlock, AD_GAIN_CODE_10V, AIOUSB_FALSE );
in the mean time. im pretty sure it would get over written by the individual set anyways according to the JSON output.

output of program with battery in positive input mode.

Serial number of device at index 0: 40e3e78c6a764f89
{"adcconfig":{"channels":[{"gain":"+-2V"},{"gain":"+-2V"},{"gain":"+-2V"},{"gain":"+-2V"},{"gain":"+-2V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"}],"calibration":"Normal","trigger":{"reference":"sw","edge":"rising-edge","refchannel":"single-channel"},"start_channel":"0","end_channel":"4","oversample":"0","timeout":"1000","clock_rate":"1000"}}A/D settings successfully configured
Volts read:
  Channel  0 = 0.010834
  Channel  1 = 0.208591
  Channel  2 = 0.377508
  Channel  3 = 1.624628
  Channel  4 = 1.238270

output of battery in negative input mode

Serial number of device at index 0: 40e3e78c6a764f89
{"adcconfig":{"channels":[{"gain":"+-2V"},{"gain":"+-2V"},{"gain":"+-2V"},{"gain":"+-2V"},{"gain":"+-2V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"},{"gain":"0-10V"}],"calibration":"Normal","trigger":{"reference":"sw","edge":"rising-edge","refchannel":"single-channel"},"start_channel":"0","end_channel":"4","oversample":"0","timeout":"1000","clock_rate":"1000"}}A/D settings successfully configured
Volts read:
  Channel  0 = 0.009308
  Channel  1 = 0.191043
  Channel  2 = 0.283055
  Channel  3 = 0.000000
  Channel  4 = 0.000000

I could be doing something wrong but do not know what it would be...

Any help would be apprieciated.

Thanks,

**Comment by accesio** [comment]
Hi,

I verified that read_channels_test works just fine for what you are trying to do.

```bash
AIOUSB/samples/USB-AIO16-16A/read_channels_test -N 1000 --range 0-4=1
-8.246,-0.043,4.863,-0.021,-0.802167
-8.246,-0.040,4.865,-0.021,-0.804608
-8.249,-0.045,4.858,-0.021,-0.803388
-8.245,-0.040,4.865,-0.020,-0.802472
-8.249,-0.044,4.857,-0.020,-0.801251
-8.247,-0.040,4.864,-0.020,-0.799115
...etc
```


Make sure that you have connected your battery's plus terminal connected to the ground , and then the input voltage connected to the ground terminal of the battery.

      +-----------------+    GND input to AIO
      |                 |
     ===                |
     gnd             --------  + 9V
                      -----      
                        |
                        | 
                        | 
                 -------+---  Channel 0 Input to AIO
