### ISSUE TITLE
Build 63c076 does not compile

### ISSUE THREAD

**Issue by sethrkaufman** [accesio/AIOUSB#20]
Errors while performing make:
Linking C executable burst_test
/usr/bin/id: CMakeFiles/USB_AI16_16_burst_test.dir/burst_test.c.o: undefined reference to symbol 'clock_gettime@@GLIBC_2.4'
//lib/arm-linux-gnueabihf/librt.xo.1:error adding symbols: DSO missing from command line
collect2: ld returned 1 exit status
samples/USB-AI16-16/CMakeFiles/USB_AI16_16_burst_test.dir/build.make:89: recipe for target 'samples/USB_AI16-16/burst_test' failed
make[2]: *** [samples/USB-AI16-16/burst_test] Error 1
CMakeFiles/Makefile2:763: recipe for target 'samples/USB-AI16-16/CMakeFiles/USB_AI16_16_burst_test.dir/all' failed
make[1]: *** [samples/USB-AI16-16/CMakeFiles/USB_AI16_16_burst_test.dir/all] Error 2
Makefile:143: recipe for target 'all' failed
make: *** [all] Error 2

This is on a Raspberry Pi running Raspian.
Linux raspberrypi 3.18.11-v7+ #781 SMP PREEMPT arm7l GNU/Linux

**Comment by sethrkaufman** [comment]
Compiles successfully if samples/USB-AI16-16/CMakeLists.txt has the last three lines commented out.

**Comment by accesio** [comment]
I added a CMake build step that checks if  glibc is  < 2.17 and if so, it adds the -lrt library.

This fixes the CMake build, but I need to also add a build for the Makefile based build as well

**Comment by accesio** [comment]
Added fix 097f3f4 that corrects the general Makefile build for samples that depends on the functionality in librt

**Comment by accesio** [comment]
Since I haven't heard back and the latest releases fix this issue I am closing this bug.
