### ISSUE TITLE
python-dev should be listed as a prerequisite

### ISSUE THREAD

**Issue by sethrkaufman** [accesio/AIOUSB#21]
The command
cmake  -DCMAKE_INSTALL_PREFIX=/some/path/Dir  -DBUILD_PYTHON=ON ..
will not run without python-dev .

Therefore python-dev should be listed as a prerequisite, perhaps by including sudo apt-get install python-dev in the instructions.

**Comment by accesio** [comment]
Added this to the new README file and the upcoming Doxygen / documentation release.
