### ISSUE TITLE
/usr/local/lib/python*/dist-packages/AIOUSB.py returns Attribute Error

### ISSUE THREAD

**Issue by sethrkaufman** [accesio/AIOUSB#22]
In both python3.2 and python 2.7, the call to line 21:

readBuffer = DIOBuf(MAX_DIO_BYTES)

returns an error on line 2588 in /usr/local/lib/python*/dist-packages/AIOUSB.py:

def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
Attribute Error: No constructor defined

**Comment by purplefishies** [comment]
We had some craziness here with flooding and other disasters.  

Can you try a commit after 8a59e3e ? I fixed a bug related to return types where a typedef of a 64 bit integer was being interpreted as a structure pointer.    

I verified that the following expression with work 

readBuffer = DIOBuf(10000)

**Comment by accesio** [comment]
I'm closing this as we've created samples that demonstrate this : 

Version 8d46329 and file 
https://github.com/accesio/AIOUSB/blob/master/AIOUSB/samples/USB-DIO-96/dio96.py
