### ISSUE TITLE
DIO_Configure and DIO_WriteAll do not work with USB-DIO-48 ports e and f

### ISSUE THREAD

**Issue by sethrkaufman** [accesio/AIOUSB#23]
DIO_Configure did not set ports e and f to the initial values set in the pData field.
DIO_WriteAll did not set ports e and f to the values set in the pData field.

DIO_Configure was configuring the e and f ports, as shown by the following:
1. Detaching the USB port
2. Reattaching the USB port
3. USB-DIO-48 with pullups on all ports shows channels on ports e and f are 5V.
4. Run test program with DIO_Configure.
5. USB-DIO-48 with pullups on all ports shows channels on ports e and f are 0V.

DIO_Configure was initializing the a,b,c,d ports, as shown by the channels on those ports changing to 0V with:
1. Detaching the USB port
2. Reattaching the USB port
3. USB-DIO-48 with pullups on all ports shows channels on ports a,b,c,d are 5V.
4. numMaskBytes = 6;
5. char *pdata   = (char *)calloc(1, device->numDIOBytes);
6. retval = DIO_Configure(deviceIndex, AIOUSB_FALSE, outmask, &pdata );
7. USB-DIO-48 with pullups on all ports shows channels on ports a,b,c,d are 0V.

DIO_Configure was initializing the a,b,c,d ports, as shown by the channels on those ports changing to 5V with:
1. Following previous test, USB-DIO-48 with pullups on all ports shows channels on ports a,b,c,d are 0V.
4. numMaskBytes = 6;
5. char *pdata   = (char *)calloc(1, device->numDIOBytes);
6. memset(pdata, 0xFF, numMaskBytes );
7. retval = DIO_Configure(deviceIndex, AIOUSB_FALSE, outmask, &pdata );
8. USB-DIO-48 with pullups on all ports shows channels on ports a,b,c,d are 5V.

DIO_WriteAll was writing to the a,b.c.d ports, as shown by toggling the channels on those ports from 0 to 5V and back.

DIO_Write8 was able to write to all ports,
		for (i = 0; i < device->numDIOBytes; i++) {
			DIO_Write8( deviceIndex, i, 0xFF );
		}

**Comment by accesio** [comment]
These issues have been fixed.   Please examine the sample under USB-DIO-96
