### ISSUE TITLE
Java_AIOUSB.c:238:2: error: too many arguments to function ?AIOUSB_GetStreamingBlockSize?

### ISSUE THREAD

**Issue by kbehrent** [accesio/AIOUSB#24]
I am trying to code you libraries working on a BeagleBone Black rev C running Debian Image 2015-03-0.

I found that the lib*.a & lib*.so files provided for linux in your distribution was not compatible to the BeagleBone so I had to rebuild them on the BeagleBone itself.  I also found that the provided aiousb.jar would also no work, so I attempted to regenerate it on the BeagleBone but encountered the following error when invoking make all in $ROOT_INSTALL/AIOUSB/java.

gcc -DNDEBUG -Wall -pthread -fPIC lib/Java_AIOUSB.c -laiousb -lusb-1.0 -o lib/libjavaaiousb.so -shared -Wl,-soname,libjavaaiousb.so
lib/Java_AIOUSB.c: In function ?Java_com_acces_aiousb_USBDevice_getStreamingBlockSize?:
lib/Java_AIOUSB.c:238:2: error: too many arguments to function ?AIOUSB_GetStreamingBlockSize?
/root/AIOUSB-master/AIOUSB/lib/AIOUSB_Core.h:109:20: note: declared here
make: *** [lib/libjavaaiousb.so] Error 1

I'm also concerned that your make files output a message stating that the code is deprecated and no longer supported. My company took a risk in trying to incorporate your board into our product solution after being assured that you support both the BeagleBone environment and java. If you no longer support your libraries in these environment, I need to know so we can pursue other alternatives.

**Comment by accesio** [comment]
Hi,

The C++ classlib wrapper code is in fact deprecated. However, all of the C code is supported and it presents functionality as a library for Java code. You will need to examine the directory called "wrappers" and use the GNUMakefile to build the java wrappers.

The instructions are under the *How to build Wrapper languages* section of the README.md file.  Essentially, after you source the **sourceme.sh** file, build the library under the **lib** directory, then you can build the java code with 

```bash
make -f GNUMakefile inplace_java
```

Please let us know which types of samples you are trying to get working and we'll be happy to help you out.

**Comment by kbehrent** [comment]
*Jimi,*

*Thanks for responding with the info, however unfortunately we still can't
get things to work completely.*

*I successfully built the lib*.a and *.so library files in AIOUSB/lib
directory. I copied them to /usr/share/java.*

*I than followed the directions to compile the wrappers in
AIOUSB/lib/wrappers executing the following:*

make -f GNUMakefile inplace_java

*Although it did build the AIOUSB.jar and libAIOUSB.so files, I got the
following output that looks suspicious:*

cd java && make -f GNUMakefile java_test
make[1]: Entering directory `/root/AIOUSB-master/AIOUSB/lib/wrappers/java'
AIOUSB.i:381: Warning 302: Identifier 'size' redefined (ignored),
../../DIOBuf.h:19: Warning 302: previous definition of 'size'.
AIOUSB.i:343: Warning 303: %extend defined for an undeclared class AIOBuf.
mkdir -p test_dir
0
ACCES devices
Result code is AIOUSB_ERROR_FILE_NOT_FOUND
true
true
make[1]: Leaving directory `/root/AIOUSB-master/AIOUSB/lib/wrappers/java'
root@bbb4:~/AIOUSB-master/AIOUSB/lib/wrappers#


*I copied the newly generated AIOUSB.jar and libAIOUSB.so files to
/usr/share/java.*

*I than tried to compile the Sample.java file within the
AIOUSB/lib/wrappers/java directory using the following command:*

javac -cp /usr/share/java/AIOUSB.jar Sample.java

*I get the following java compiler errors:*

root@bbb4:~/AIOUSB-master/AIOUSB/lib/wrappers/java# javac -cp
/usr/share/java/AIOUSB.jar Sample.java

Sample.java:23: error: cannot find symbol

            AIOUSB.AIOContinuousBuf_SetDeviceIndex( buf, 0 );

                  ^

  symbol:   method AIOContinuousBuf_SetDeviceIndex(AIOContinuousBuf,int)

  location: class AIOUSB

Sample.java:24: error: cannot find symbol

            AIOUSB.AIOContinuousBuf_InitConfiguration( buf );

                  ^

  symbol:   method AIOContinuousBuf_InitConfiguration(AIOContinuousBuf)

  location: class AIOUSB

Sample.java:25: error: cannot find symbol

            AIOUSB.AIOContinuousBuf_SetOverSample( buf, 0 );

                  ^

  symbol:   method AIOContinuousBuf_SetOverSample(AIOContinuousBuf,int)

  location: class AIOUSB

Sample.java:26: error: cannot find symbol

            AIOUSB.AIOContinuousBuf_SetStartAndEndChannel( buf, 16, 31 );

                  ^

  symbol:   method
AIOContinuousBuf_SetStartAndEndChannel(AIOContinuousBuf,int,int)

  location: class AIOUSB

Sample.java:27: error: cannot find symbol

            AIOUSB.AIOContinuousBuf_SetAllGainCodeAndDiffMode( buf ,
ADGainCode.AD_GAIN_CODE_0_2V, AIOUSB_BOOL_VAL.AIOUSB_TRUE );

                  ^

  symbol:   method
AIOContinuousBuf_SetAllGainCodeAndDiffMode(AIOContinuousBuf,ADGainCode,AIOUSB_BOOL_VAL)

  location: class AIOUSB

Sample.java:28: error: cannot find symbol

            AIOUSB.AIOContinuousBuf_SaveConfig(buf);

                  ^

  symbol:   method AIOContinuousBuf_SaveConfig(AIOContinuousBuf)

  location: class AIOUSB

Sample.java:42: error: incomparable types: long and THREAD_STATUS

                if( read_count > max_count ||
AIOUSB.AIOContinuousBufGetStatus( buf ) != THREAD_STATUS.RUNNING ) {


          ^

Sample.java:51: error: incompatible types: possible lossy conversion from
long to int

                    retval = AIOUSB.AIOContinuousBufGetExitCode( buf );

                                                               ^

Sample.java:62: error: cannot find symbol


AIOUSB.AIOContinuousBufGetSize( buf ),

                                                        ^

  symbol:   method AIOContinuousBufGetSize(AIOContinuousBuf)

  location: class AIOUSB

Sample.java:72: error: cannot find symbol

                    for( int i = 0, ch = 0 ; i < retval; i ++, ch = ((ch+1)
% (int)AIOUSB.AIOContinuousBuf_NumberChannels(buf)) ) {


              ^

  symbol:   method AIOContinuousBuf_NumberChannels(AIOContinuousBuf)

  location: class AIOUSB

Sample.java:74: error: cannot find symbol

                        if( ((i+1) %
(int)AIOUSB.AIOContinuousBuf_NumberChannels(buf)) == 0 ) {

                                                ^

  symbol:   method AIOContinuousBuf_NumberChannels(AIOContinuousBuf)

  location: class AIOUSB

11 errors

root@bbb4:~/AIOUSB-master/AIOUSB/lib/wrappers/java#

*At this point, I'm just trying to get any of the java samples to work,
although none of them are specific to the USB-DIO-48 that we are currently
testing.*


*Thanks,*

*Kevin*

On Mon, Mar 21, 2016 at 9:44 PM, Jimi Damon <notifications@github.com>
wrote:

> Hi,
>
> The C++ classlib wrapper code is in fact deprecated. However, all of the C
> code is supported and it presents functionality as a library for Java code.
> You will need to examine the directory called "wrappers" and use the
> GNUMakefile to build the java wrappers.
>
> The instructions are under the *How to build Wrapper languages* section
> of the README.md file. Essentially, after you source the *sourceme.sh*
> file, build the library under the *lib* directory, then you can build the
> java code with
>
> make -f GNUMakefile inplace_java
>
> Please let us know which types of samples you are trying to get working
> and we'll be happy to help you out.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/accesio/AIOUSB/issues/24#issuecomment-199635453>
>



-- 
Kevin Behrent
Cell: 253-906-6674
Email: kbehrent@gmail.com

**Comment by accesio** [comment]
Hi Kevin,

Some fixes were just checked in with release e71ca5d that address the problems Java was seeing.  Can you try downloading this version and let me know if you these problems have, in fact, gone away for you.

-Jimi

**Comment by accesio** [comment]
Please don't pull yet. I incorrectly checked in a wrong branch. I will Post shortly with the correct release.

**Comment by accesio** [comment]
Hi Kevin,

The newest changes were rebased over the original master.  You will need to repull and get the version that corresponds to release bd627a9 .   Let me know if this helps with your Java issues.

-Jimi

**Comment by kbehrent** [comment]
Jimi,

Your fix seems to work for AIOUSB/sample/USB-DIO-32/Sample.java. It did not
work for the AIOUSB/lib/wrappers/java/Sample.java.

We will now attempting to connect the USB-DIO-48 to the BeagleBone and see
if we can communicate with it.

Thanks,
Kevin

On Tue, Mar 22, 2016 at 1:02 PM, Jimi Damon <notifications@github.com>
wrote:

> Hi Kevin,
>
> The newest changes were rebased over the original master. You will need to
> repull and get the version that corresponds to release bd627a9
> <https://github.com/accesio/AIOUSB/commit/bd627a9e470ab96e3fd1e41efd5409c606353c72>
> . Let me know if this helps with your Java issues.
>
> -Jimi
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/accesio/AIOUSB/issues/24#issuecomment-199993835>
>



-- 
Kevin Behrent
Cell: 253-906-6674
Email: kbehrent@gmail.com

**Comment by accesio** [comment]
Please ignore and samples under AIOUSB/lib/wrappers/java/Sample.java

**Comment by lyesba** [comment]
Hello
I am for help,
I want to install AIOUSB a raspberry to install it works but compilation I use your control but it also works the execution I have an error message "./test: error while loading shared libraries: libaiousbcpp.so: can not oprn shared object file: No such file or diractory "

**Comment by accesio** [comment]
After  the **source sourceme.sh** step,  did you try running a sample with

LD_LIBRARY_PATH="${AIO_LIB_DIR}:${AIO_CLASSLIB_DIR}:$(pwd)" java -classpath "${AIO_LIB_DIR}/lib/wrappers/java/AIOUSB.jar:${OTHER_CLASSPATH}"  your_java_class   ?

**Comment by accesio** [comment]
Closed
