### ISSUE TITLE
AIOUSB.AIOUSB_GetVersionDate() returns "$Format: %ad$" instead of version date string

### ISSUE THREAD

**Issue by kbehrent** [accesio/AIOUSB#26]
AIOUSB.AIOUSB_GetVersionDate() incorrectly returns "$Format: %ad$" instead of version date string.

**Comment by accesio** [comment]
if you want these to return correct values, use the Zip version

**Comment by kbehrent** [comment]
Do you mean the zip file has more updated code than what it in the github
repository?

On Wed, Mar 23, 2016 at 7:13 PM, Jimi Damon <notifications@github.com>
wrote:

> if you want these to return correct values, use the Zip version
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/accesio/AIOUSB/issues/26#issuecomment-200618238>
>



-- 
Kevin Behrent
Cell: 253-906-6674
Email: kbehrent@gmail.com

**Comment by accesio** [comment]
These values are expanded correctly when you download a full zip file  or a release as opposed to when you **clone** the repo.
