### ISSUE TITLE
python _AIOSUB.so undefined symbol: Newintlist

### ISSUE THREAD

**Issue by rlegault33** [accesio/AIOUSB#29]
importing AIOUSB error

>>> import AIOUSB
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "AIOUSB.py", line 28, in <module>
    _AIOUSB = swig_import_helper()
  File "AIOUSB.py", line 24, in swig_import_helper
    _mod = imp.load_module('_AIOUSB', fp, pathname, description)
ImportError: mfgtest/models/daq/_AIOUSB.so: undefined symbol: Newintlist1

git log
commit 2076dbde0b9313406f968ea99023509a15d85cbf
Author: Jimi Damon <jdamon@accesio.com>
Date:   Thu May 26 13:33:59 2016 -0700

    ENH: fn for retrieving errno status

**Comment by rlegault33** [comment]
I cleared out usr/local/lib/libaio*
and then did an install to insure the latest libaiousb objects were present.
Ubuntu 16.04
python 2.7.11+

**Comment by jeetmehta** [comment]
Tested with f18d3e63 and the import issue has been fixed.
Thanks.
