### ISSUE TITLE
AIOUSBDeviceWriteADCConfig() returns errorcode 21 (python)

### ISSUE THREAD

**Issue by rlegault33** [accesio/AIOUSB#32]
Getting the error result with git pull: 099c54dee56a158620309e91ad4e0aaa16f51031
Ubuntu 16.04
Python 2.7.12
Here is the python code that illustrates the problem. Modified the code from AI16-16/.../sample.py that easiest shows the problem.

>>> import sys
>>> import time
>>> import math
>>> import os
>>> sys.path.append("/home/user/GIT/AIOUSB/AIOUSB/build/lib/wrappers/python")
>>> import AIOUSB
>>> from AIOUSB import *
>>> AIOUSB_GetVersion()
'$Format: %h$'
>>> AIOUSB_GetVersionDate()
'$Format: %ad$'
>>> options = NewAIOCommandLineOptionsFromDefaultOptions( AIO_SCRIPTING_OPTIONS() )
>>> device_indices = []
>>> AIOUSB_FindDevicesByGroup( device_indices, AIOUSB.AIO_ANALOG_INPUT() )
>>> def find_ai(obj):
...     if (obj.PID >= USB_AI16_16A and obj.PID <= USB_AI12_128E) or \
...        (obj.PID >=  USB_AIO16_16A and obj.PID <= USB_AIO12_128E ):
...         return True
... 
>>> device_indices = AIOUSB_FindDevices( find_ai )
>>> device_indices
[0]
>>> deviceIndex = device_indices[0]
>>> AIOUSB_Reset( deviceIndex );
0L
>>> AIOUSB_SetCommTimeout( deviceIndex, 1000 );
0L
>>> AIOUSB_SetDiscardFirstSample( deviceIndex, AIOUSB_TRUE );
0L
>>> [ndevice,result] = AIODeviceTableGetDeviceAtIndex( deviceIndex )
>>> ndevice
<AIOUSB.AIOUSBDevice; proxy of <Swig Object of type 'struct AIOUSBDevice *' at 0x7fe7fc57d810> >
>>> result
0L
>>> cb = AIOUSBDeviceGetADCConfigBlock( ndevice )
>>> cb
<AIOUSB.ADCConfigBlock; proxy of <Swig Object of type 'ADCConfigBlock *' at 0x7fe7fabfbd20> >
>>> AIOUSB_SetAllGainCodeAndDiffMode( cb, AD_GAIN_CODE_10V, AIOUSB_FALSE );
0L
>>> ADCConfigBlockSetCalMode( cb, AD_CAL_MODE_NORMAL );
0L
>>> ADCConfigBlockSetTriggerMode( cb, 0 );
0L
>>> ADCConfigBlockSetScanRange( cb, 2, 13 );
0L
>>> ADCConfigBlockSetOversample( cb, 0 );
0L
>>> AIOUSBDeviceWriteADCConfig( ndevice, cb );
21L
>>> AIOUSB_GetResultCodeAsString(21)
'UNKNOWN'

**Comment by rlegault33** [comment]
The error was introduced with git commit aa88efb
CLN: cleanup warning errors with clang

**Comment by accesio** [comment]
Hi,

The issue is that Linux return codes use negative numbers to indicate error and >= 0 to typically indicate that the 0 or more bytes were written to the device.  This is the case for AIOUSBDeviceWriteADConfig.

The issue is that the Windows API is terrible ( returning unsigned long vs  signed long )  and in order to make progress and have error codes that are actually useful we needed to break with the convention.

Sorry about this
