### ISSUE TITLE
Error in compiling the AIOUSB package using Cmake

### ISSUE THREAD

**Issue by Vineet-Pandey** [accesio/AIOUSB#35]
**OS: Ubuntu 16.04**

After installing libusb library, compiling the AIOUSB package using cmake gives an error while building the executables using the following command:
cd AIOUSB
mkdir build
cd build
cmake ..
make

Error:

c++: error: Interface/AIOUSB-master/AIOUSB/deprecated/classlib/../lib: No such file or directory
deprecated/classlib/CMakeFiles/classaiousb.dir/build.make:850: recipe for target 'deprecated/classlib/libclassaiousb.so' failed
make[2]: *** [deprecated/classlib/libclassaiousb.so] Error 1
CMakeFiles/Makefile2:430: recipe for target 'deprecated/classlib/CMakeFiles/classaiousb.dir/all' failed
make[1]: *** [deprecated/classlib/CMakeFiles/classaiousb.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by accesio** [comment]
I need some feedback about what is going wrong .
Whihc platform are you using and which version ( git log ) of the code are you using ? 
The following commands build the code  for master : 

git clone https://github.com/accesio/AIOUSB.git

cd AIOUSB/AIOUSB/

mkdir build

cd build

cmake ..

make -j4

**Comment by Vineet-Pandey** [comment]
Platform: Ubuntu 16.04 (using Cmake)
I am using the Master repository.
