### ISSUE TITLE
Compile errors and other issues

### ISSUE THREAD

**Issue by severach** [accesio/AIOUSB#36]
gcc 7.1 reports an ambiguous abs() problem. See [patch](https://github.com/accesio/AIOUSB/files/1227312/0000-cpp-abs-ambiguous.patch.zip) for fix.
````
[  9%] Building CXX object lib/CMakeFiles/aiousbcppdbg.dir/AIOUSB_ADC.dbg.cpp.o
/tmp/makepkg/accesio-aiousb/src/AIOUSB-cfdbc9ab6a5e1b36cff7daba0954e68313344ed6/AIOUSB/build/lib/AIOUSB_ADC.dbg.cpp: In function ‘long unsigned int AIOUSB::ADC_SetConfig(long unsigned int, unsigned char*, long unsigned int*)’:
/tmp/makepkg/accesio-aiousb/src/AIOUSB-cfdbc9ab6a5e1b36cff7daba0954e68313344ed6/AIOUSB/build/lib/AIOUSB_ADC.dbg.cpp:942:56: error: call of overloaded ‘abs(AIORESULT&)’ is ambiguous
      result = result >= 0 ? AIOUSB_SUCCESS : abs(result);
````
GNU make is incomplete. It doesn't make all samples and I don't see a make install.

accesloader.pl is not marked chmod +x and still has a .pl extension. Is this intentional?

Why don't the libs have soname versions? Do you expect them to be compatible forever?

Seg fault in /usr/share/accesio/USB_DA12_8A/SampleClass

Checking the firmwares in udev, the perl file, and /usr/share/usb reveal some missing and unreferenced firmwares
````
Can't find udev /usr/share/usb/PCIe-WDG-CSM.hex
Can't find udev /usr/share/usb/USB-AI16-16.hex
Can't find udev /usr/share/usb/USB-AIO16-16.hex
Unreferenced udev USB-AO16-16A.hex
Unreferenced udev USB-IIRO-16.hex
Unreferenced udev USBP-II8IDO4A.hex
Unreferenced perl USB-AO16-16A.hex
Unreferenced perl USB-AO-ARB1.hex
Unreferenced perl USB-DIO24-CTR6.hex
Unreferenced perl USB-DIO-32I.hex
Unreferenced perl USB-IIRO-16.hex
Unreferenced perl USBP-II8IDO4A.hex
````

All firmwares with spaces are disabled, probably because the command lines don't work with spaces. They could be put back if the spaces were removed.  The files with spaces won't work in the perl firmware uploader as implemented.

Some of the demos don't run. One library isn't installed and one is installed where it can't be found.

**Comment by accesio** [comment]
New fixes were made that should have corrected this.

**Comment by accesio** [comment]
Our Travis CI  uses both gcc and clang and the errors are gone so I'm closing this
