### ISSUE TITLE
fxload location issue

### ISSUE THREAD

**Issue by niliopoulos** [accesio/AIOUSB#8]
Hello,
Is it possible to update the instructions in the fxload repository to match the location of the udev rules in the AIOUSB repository? The suggested location in the documentation of fxload is /etc/bin, but the udev rules of the AIOUSB repository point to /sbin/fxload.

Thanks!

**Comment by JHentges** [comment]
Absolutely!
Thank you for letting us know, this will be addressed today.

**Comment by JHentges** [comment]
The fxload repo readme has been updated to reflect the preferred "/etc/bin/ location for fxload. The AIOUSB repo .rules files will be updated shortly to use the /etc/bin/fxload command instead of /sbin/fxload
